baseURL = 'https://ggemre.github.io'
languageCode = 'en-us'
title = 'ggemre'
theme = 'PaperMod'

[menus]
  [[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 1
  [[menus.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 2
  [[menus.main]]
  name = 'Docs'
  pageRef = '/docs'
  weight = 3
  [[menus.main]]
  name = 'Papers'
  pageRef = '/papers'
  weight = 4
  [[menus.main]]
  name = 'Search'
  pageRef = '/search'
  weight = 5

[outputs]
  home = ['html', 'rss', 'json']

[params.profileMode]
enabled = true
title = "Hi, I'm Gage!"
imageUrl = '/images/avatar.png'
imageWidth = 155
imageHeight = 120
  # [[params.profileMode.buttons]]
  # name = 'Archive'
  # url = '/archive'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/ggemre'
[[params.socialIcons]]
name = 'email'
url = 'mailto:gagebmoore@gmail.com'
